### ISSUE TITLE
Residential zoning boundaries for Daly City

### ISSUE THREAD

**Issue by jridener** [opensmc/ssmc-agriculture-zoning#26]
Create or download residential boundaries for Daly City. Use the zoning boundaries in the Designation column of this Google Sheet as a guide for which boundaries to download or create: https://docs.google.com/spreadsheets/d/199shxJaRycwVGXGR46jQNyur960dnPf-L7-lIcXyKRg/edit#gid=1982096394

Use http://geosjon.io to create the boundaries in geojson format. Here are the steps:
1. Go to [http://geojson.io/](http://geojson.io/)
2. Login to GitHub via geojson.io
3. Using your zoning boundary map as a source, create the polygon for each residential boundary
4. You likely have more than one polygon for each boundary type, this is OK!
5. Save as a local copy as you work; click Save > GeoJSON
6. When you're done and ready to push the boundary data to GitHub, click Save > GitHub 
7. Save to opensmc/ssmc-agriculture-zoning/master/zoning-boundaries/NewFile
8. Name the file the city name

**Comment by rareitmeyer** [comment]
I will call Daly City to see if they have better data available.

**Comment by rareitmeyer** [comment]
Spoke with Daly City. They're going to look into what they have and get back to me.

**Comment by rareitmeyer** [comment]
Daly City has a GIS person, John S, working in the public works department (not the planning dept). Trying to reach him for data files.

**Comment by rareitmeyer** [comment]
John S at Daly City provided ESRI shape files. I've checked in the raw data into a DALY_CITY directory, and a GeoJSON export (WGS84) into zoning_boundaries/daly_city.geojson. Closing ticket.
