### ISSUE TITLE
Residential zoning boundaries for Pacifica

### ISSUE THREAD

**Issue by jridener** [opensmc/ssmc-agriculture-zoning#31]
Create or download residential boundaries for Pacifica. Use the zoning boundaries in the Designation column of this Google Sheet as a guide for which boundaries to download or create: https://docs.google.com/spreadsheets/d/199shxJaRycwVGXGR46jQNyur960dnPf-L7-lIcXyKRg/edit#gid=1982096394

Use http://geosjon.io to create the boundaries in geojson format. Here are the steps:
1. Go to [http://geojson.io/](http://geojson.io/)
2. Login to GitHub via geojson.io
3. Using your zoning boundary map as a source, create the polygon for each residential boundary
4. You likely have more than one polygon for each boundary type, this is OK!
5. Save as a local copy as you work; click Save > GeoJSON
6. When you're done and ready to push the boundary data to GitHub, click Save > GitHub 
7. Save to opensmc/ssmc-agriculture-zoning/master/zoning-boundaries/NewFile
8. Name the file the city name

**Comment by rareitmeyer** [comment]
I will call Pacifica to see if they have a better data source available than the current multi-page PDF.

**Comment by rareitmeyer** [comment]
Called Pacifica, spoke with planner Robert Smith. The city does not have GIS files: a consultant who worked with them back when they did their general plan might, but has not shared the data. The best map of zoning boundaries is indeed the black-and-white thing spread over ~20 pages in the draft general plan document.

**Comment by jridener** [comment]
I'll bring a print out and some tape for hack night. We can create GIS for
Pacifica!

**Comment by rareitmeyer** [comment]
That sounds great!
But I have a conflict in Mtn View. Will check times to see if I can get to Redwood City briefly first. If not, do you think OpenGov would hold onto the printouts for me until tomorrow?

**Comment by jridener** [comment]
I can ask. I'm hoping we might be able to create the paper map tonight
unless that would make further transportation impossible. What's your
preference?

**Comment by rareitmeyer** [comment]
If you can do the printing, I can do the cutting and taping. My Mnt View meeting starts at 6:30, so if you are at OpenGov at 6, I can pick up at 6.

**Comment by jridener** [comment]
I have the printed PDF in my hands. Will bring it to OpenGov for 6.

**Comment by rareitmeyer** [comment]
Was able to steal a table in back of other meeting, and started with folding version just to see.
It does not line up as nicely as the AAA maps did.
If i gave you a new PDF by next week's meeting, could you print it?

**Comment by jridener** [comment]
Sorry to hear that! Definitely can print a new one whenever. Greg mentioned
he could stitch together in Photoshop as well if that's easier.

**Comment by rareitmeyer** [comment]
Yes, that was what I was going to do.

-------- Original message --------

**Comment by jridener** [comment]
I was so excited to see the finished taped product!

**Comment by rareitmeyer** [comment]
Made a QGIS map with all the Pacifica streets and parcels (clipped SMC map to city boundaries), and have started a mondo map of the Pacifia zoning in GIMP, the open-source photoshop alternative. Have added a PACIFICA directory with some notes. Currently about half-way done with assembling mondo map in GIMP.

**Comment by rareitmeyer** [comment]
I've been ignoring the + (voting required to change) annotation, and the -H (hillside) annotation, so I have coded R-1-H zones, and R-1 zones, as R-1.

Do the city bylaws make a difference between R-1 and R-1-H for anything we'd care about?

**Comment by jridener** [comment]
There's no difference between any of the zoning areas in Pacifica. We'll
see if SSMC's confirmation with cities says something different.

**Comment by rareitmeyer** [comment]
Thanks, John. I have also skipped the "B" lot size overlays, which I expect not to make a difference either.

Roughly 70% done now: on panel 34/47. Will upload progress shortly.

**Comment by rareitmeyer** [comment]
Finished, to my ability to interpret how the 2001 map applies to 2016 parcels. Where almost all of a parcel is in a single zone, I've opted to assign that zone... which is wrong for the part of the parcel not in the zone, but hopefully not "too wrong." For parcels where more than about 10% of the area of a parcel is in a different zone, I've usually tried to leave the zone blank.

It might be useful to refine this by meeting with the Pacifica planning department. That might best be viewed as a separate issue, so closing.

**Comment by jridener** [comment]
@rareitmeyer: I see a .qgs file in the /PACFICA directory, but no shapefile or geojson for the boundaries. Likely I'm not seeing correctly though.

**Comment by rareitmeyer** [comment]
Are you looking at https://github.com/opensmc/ssmc-agriculture-zoning/tree/master/PACIFICA? When I look at it, it shows several shapefiles, most notably parcels.{dbf,prj,shp,shx}. 

The PACIFICA directory has all my 'raw' work in hope it helps the next person, so that's where I put the shapefiles, QGIS project, PDF, and even a GIMP stack of ~90 layers to assemble the panels by hand, if someone wanted to.

But the completed geojson file is the completed work(*), and so I put that in the zoning_boundaries directory at https://github.com/opensmc/ssmc-agriculture-zoning/blob/master/zoning_boundaries/pacifica.geojson

Please write back if the files are not there.

(*) not to minimize the additional work you are doing to enforce conformity on the files.

**Comment by jridener** [comment]
My mistake! I saw the parcels files and thought they were the County parcel
layer. I'll work from those.
