### ISSUE TITLE
Residential zoning boundaries for Menlo Park

### ISSUE THREAD

**Issue by jridener** [opensmc/ssmc-agriculture-zoning#33]
Create or download residential boundaries for Menlo Park. Use the zoning boundaries in the Designation column of this Google Sheet as a guide for which boundaries to download or create: https://docs.google.com/spreadsheets/d/199shxJaRycwVGXGR46jQNyur960dnPf-L7-lIcXyKRg/edit#gid=1982096394

Use http://geosjon.io to create the boundaries in geojson format. Here are the steps:
1. Go to [http://geojson.io/](http://geojson.io/)
2. Login to GitHub via geojson.io
3. Using your zoning boundary map as a source, create the polygon for each residential boundary
4. You likely have more than one polygon for each boundary type, this is OK!
5. Save as a local copy as you work; click Save > GeoJSON
6. When you're done and ready to push the boundary data to GitHub, click Save > GitHub 
7. Save to opensmc/ssmc-agriculture-zoning/master/zoning-boundaries/NewFile
8. Name the file the city name

**Comment by rareitmeyer** [comment]
The Menlo Park planning department has a GIS extract available at https://data.menlopark.org/Government/Parcels-GIS-format-/r4jv-ruxn --- I'm in conversation with them to confirm zoning is in the "gpz_gen_pl" and "gp1_value" columns as the zone abbreviation and full name for each parcel. If so, that will be great.

**Comment by rareitmeyer** [comment]
Confirmed, the "gpz_gen_pl" column is the zoning.

Question for John: can file be used as-is, or does it need to be brought into the same list of columns as other cities?

**Comment by jridener** [comment]
We can definitely use this file! I'll add it to the repo. Thanks Richard!

**Comment by jridener** [comment]
Residential zoning boundaries for Menlo Park extracted from City of Menlo Park's file posted here: ssmc-agriculture-zoning/zoning_boundaries/

**Comment by rareitmeyer** [comment]
For what it's worth, the person that helped me was Thomas Rogers, in the planning department.
