### ISSUE TITLE
Redwood City zoning code review

### ISSUE THREAD

**Issue by jridener** [opensmc/ssmc-agriculture-zoning#45]
Review the zoning code for Redwood City: https://www.municode.com/library/ca/redwood_city/codes/zoning to see if the zoning code allows residents to keep animals (especially chickens), bees, or have gardens located anywhere on their property.

We're looking at residential areas only, so R-1 through R-5 designations only

Add the results to this Google Sheet: https://docs.google.com/spreadsheets/d/199shxJaRycwVGXGR46jQNyur960dnPf-L7-lIcXyKRg/edit?usp=sharing

**Comment by ShellSV** [comment]
Done!
