### ISSUE TITLE
Merge residential zoning boundaries by city

### ISSUE THREAD

**Issue by jridener** [opensmc/ssmc-agriculture-zoning#52]
The residential zoning boundaries by city are here: https://github.com/opensmc/ssmc-agriculture-zoning/tree/master/zoning_boundaries

In desktop GIS, merge these boundaries by zoning code for each city. The result should be 1 multipart polygon for a zoning boundary type for each city.

Load the simplified boundaries to a new directory for simplified boundaries on GitHub

**Comment by weverka** [comment]
Is there a directory for simplified boundaries yet?

**Comment by jridener** [comment]
Not yet. When you save the first file, you can create the directory (unless there's a permissions issue). I would recommend a name like '/simplified_zoning_boundaries'
