### ISSUE TITLE
Remove East Palo Alto Raw Directory from Zoning Boundaries

### ISSUE THREAD

**Issue by benvogcodes** [opensmc/ssmc-agriculture-zoning#58]
As there is a finished geojson file for East Palo Alto, is the directory of "in progress" notes, etc obsolete now?

**Comment by rareitmeyer** [comment]
East Palo Alto is done, and has been done for a while. I uploaded all the "raw" content with intent to aid whoever does EPA next. In conversations with the EPA city staff, they are in the midst of redoing all of their zoning right now --- new zoning could be final toward the end of 2016, or early 2017, depending on what the city council decides. So I'd leave it, personally.
