### ISSUE TITLE
Initial 3Bs map view at user location

### ISSUE THREAD

**Issue by jridener** [opensmc/ssmc-agriculture-zoning#61]
Map is located at: https://opensmc.carto.com/viz/71e3c5bc-9014-11e6-9b53-0e233c30368f/public_map

Need to figure out if we can get estimated user location. Second choice would be to start at a moderate zoom level that shows the County from San Mateo to Redwood City.

**Comment by Lillian-wang** [comment]
Hi John, I have just added geolocation detection to the map. If you are within a bounded square on the map, roughly respresenting the bay area, you will be zoomed in. 
Here is the demo: https://lillian-wang.github.io/openSMC_geo_location_demo.html
