### ISSUE TITLE
Allow users to select from bees, chickens, or gardens layer using an always-open legend box with sliders

### ISSUE THREAD

**Issue by jridener** [opensmc/ssmc-agriculture-zoning#64]
The out-of-the-box functionality for CARTO requires users to click on a blank white box to switch layers: https://opensmc.carto.com/viz/71e3c5bc-9014-11e6-9b53-0e233c30368f/public_map

It seems possible to use CARTO css to add an always-open box that would allow a user to turn on 1 - 3 layers at a time and display the corresponding legend on the map.

**Comment by weverka** [comment]
Took a pass at starting this here: https://github.com/opensmc/ssmc-agriculture-zoning/blob/master/SSMC_3Bs.html. It could use some improvement with button styling so assistance from a CSS/Javascript user would be much appreciated!

**Comment by verythorough** [comment]
This works nicely!  I'll take a stab at some of the styling later.

**Comment by Lillian-wang** [comment]
Hey guys, this is my solution: https://lillian-wang.github.io/openSMC_layer_selector_demo.html. Source code: https://github.com/Lillian-wang/Lillian-wang.github.io/blob/master/openSMC_layer_selector.html. If this is ok, which file do I edit to create a pull request?

**Comment by jridener** [comment]
This would be a new file since we have been working on the assumption that
the map would be embedded on the SSMC WordPress site
www.sustainablesanmateo.org

I have a login to the site and am meeting with SSMC Monday. I can show your
site and see how we can get your code into their site.

Thanks for this!
